"""Context Control Center (M3.5 P0-2/P0-3): what ROOK is connected to, what it can actually read, how fresh it is,
and how complete the user's context is.

Everything here is derived from real state — connector rows, stored OAuth grants, the latest sync outcome, and
items *this user can see*. Nothing is hard-coded, and counts never include items the user cannot open. The web UI
renders these values; it never works out access or health itself.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..connectors import REGISTRY
from ..models import Connector, ConnectorCredential, Signal, User, utcnow
from ..trust import FACT, INFERENCE
from .meetings import visible_meetings
from .permissions import can_view
from .views import iso

TAGLINE = "ROOK continuously builds context from the systems your organization already uses."

# Context types in the order users think about them, with plain-language names.
CONTEXT_TYPES = {
    "meetings": "Meetings",
    "conversations": "Conversations",
    "transcripts": "Meeting transcripts",
    "work_items": "Work items",
    "documents": "Documents",
}
SIGNAL_CONTEXT = {"email": "conversations", "message": "conversations", "meeting_transcript": "transcripts",
                  "task_update": "work_items", "document": "documents"}

# What each OAuth permission lets ROOK do, in words (Microsoft Graph delegated scopes; read-only unless stated).
SCOPE_LABELS = {
    "openid": "Sign you in",
    "profile": "Read your basic profile",
    "email": "Read your email address",
    "offline_access": "Stay connected without asking you to sign in again",
    "User.Read": "Read your basic profile",
    "Mail.Read": "Read your mail",
    "Calendars.Read": "Read your calendar",
    "OnlineMeetings.Read": "Read your Teams meeting details",
    "OnlineMeetingTranscript.Read.All": "Read Teams meeting transcripts you can access (admin consent)",
    "Mail.Send": "Send mail — only messages you approve",
}

ACCESS_LABELS = {
    "available": "Available",
    "granted": "Granted — not synchronized yet",
    "not_granted": "Permission not granted",
    "admin_required": "Administrator permission required",
    "disabled": "Turned off on this server",
    "unavailable": "Unavailable",
    "disconnected": "Not connected",
}

STALE_AFTER = timedelta(hours=24)


def _parse(ts: str | None) -> datetime | None:
    return datetime.fromisoformat(ts.rstrip("Z")) if ts else None


def _visible_counts(db: Session, user: User, connector_id: int | None = None) -> Counter:
    q = select(Signal).where(Signal.org_id == user.org_id)
    if connector_id is not None:
        q = q.where(Signal.connector_id == connector_id)
    counts: Counter = Counter()
    for s in db.scalars(q).all():
        if can_view(user, s):
            counts[SIGNAL_CONTEXT.get(s.kind, "conversations")] += 1
    meetings = [m for m in visible_meetings(db, user) if connector_id is None or m.connector_id == connector_id]
    counts["meetings"] += len(meetings)
    return counts


def _access(cls, conn: Connector, granted: set[str], last: dict | None) -> list[dict]:
    """What ROOK can actually read from this connection, per kind of data, with the reason when it can't."""
    gaps = (last or {}).get("gaps", {})
    out = []
    for dt in cls.data_types:
        if conn.status == "disconnected":
            status, reason = "disconnected", "Disconnected: ROOK no longer reads this source."
        elif dt.key in gaps:
            status, reason = gaps[dt.key]["status"], gaps[dt.key]["reason"]
        elif not cls.delegated:
            status, reason = "available", "Synthetic data generated by ROOK." if cls.synthetic else "Provided to your organization."
        elif missing := [s for s in dt.scopes if s not in granted]:
            status = "admin_required" if dt.admin_consent else "not_granted"
            reason = (f"Needs {', '.join(missing)}, which an administrator must approve for your organization."
                      if dt.admin_consent else f"You did not grant {', '.join(missing)}. Reconnect to grant it.")
        elif not conn.last_synced_at:
            status, reason = "granted", "Permission granted. ROOK has not completed a sync yet."
        else:
            status, reason = "available", "Permission granted and read at the last sync."
        out.append({"key": dt.key, "label": dt.label, "context": dt.context, "status": status,
                    "status_label": ACCESS_LABELS[status], "reason": reason, "ok": status == "available"})
    return out


def _actions(cls, conn: Connector, user: User) -> list[str]:
    """Only actions the API will accept from this user (enforced again in the routes)."""
    if not cls.implemented or cls.kind == "manual":
        return []
    acts = []
    if conn.status != "disconnected":
        acts.append("sync")
    if cls.delegated and cls.is_configured():
        acts.append("reconnect")
    if conn.status != "disconnected" and (cls.delegated or (user.role == "admin" and not cls.synthetic)):
        acts.append("disconnect")
    return acts


def _connection(db: Session, user: User, conn: Connector, cls) -> dict:
    cred = db.scalar(select(ConnectorCredential).where(ConnectorCredential.connector_id == conn.id))
    granted = set(cred.scopes.split()) if cred and cred.scopes else set()
    owner = db.get(User, conn.created_by) if conn.created_by else None
    last = (conn.config or {}).get("last_sync")
    counts = _visible_counts(db, user, conn.id)
    return {
        "id": conn.id,
        "status": conn.status,
        "account": owner.email if cls.delegated and owner else ("Synthetic demo organisation" if cls.synthetic else "Your organization"),
        "last_attempted_sync": last["at"] if last else None,
        "last_successful_sync": iso(conn.last_synced_at),
        "last_sync": last,
        "granted_permissions": [{"scope": s, "label": SCOPE_LABELS.get(s, s)} for s in sorted(granted)],
        "access": _access(cls, conn, granted, last),
        "visible_items": {k: counts.get(k, 0) for k in CONTEXT_TYPES},
        "actions": _actions(cls, conn, user),
    }


def sources(db: Session, user: User) -> list[dict]:
    rows = db.scalars(select(Connector).where(Connector.org_id == user.org_id)).all()
    out = []
    for kind, cls in REGISTRY.items():
        # Delegated connectors are per user: show only the caller's own connection, never a colleague's account.
        conn = next((r for r in rows if r.kind == kind and (not cls.delegated or r.created_by == user.id)), None)
        if kind == "manual" and conn is None:
            continue  # uploads appear once something has been uploaded
        connected = conn is not None and conn.status != "disconnected"
        out.append({
            "kind": kind,
            "name": cls.display_name,
            "suite": cls.suite,
            "category": cls.category,
            "implemented": cls.implemented,
            "synthetic": cls.synthetic,
            "delegated": cls.delegated,
            "connectable": cls.implemented and cls.delegated and cls.is_configured() and not connected,
            "setup_required": cls.implemented and cls.delegated and not cls.is_configured(),
            "data_types": [{"key": d.key, "type": d.context, "label": d.label} for d in cls.data_types],
            "requested_permissions": [{"scope": s, "label": SCOPE_LABELS.get(s, s)} for s in cls.scopes],
            "sending": "enabled — only messages you approve" if cls.sending_enabled() and cls.can_send else "off",
            "state": "connected" if connected else ("available" if cls.implemented else "later"),
            "connection": _connection(db, user, conn, cls) if conn is not None else None,
        })
    order = {"connected": 0, "available": 1, "later": 2}
    return sorted(out, key=lambda s: (order[s["state"]], s["name"]))


def available_later(srcs: list[dict]) -> list[dict]:
    """Registered but not built: grouped by product family, never offered as connectable."""
    groups: dict[str, dict] = {}
    for s in srcs:
        if s["state"] != "later":
            continue
        g = groups.setdefault(s["suite"] or s["name"], {"name": s["suite"] or s["name"], "products": [], "data_types": []})
        g["products"].append(s["name"])
        g["data_types"] += [d["label"] for d in s["data_types"] if d["label"] not in g["data_types"]]
    return sorted(groups.values(), key=lambda g: g["name"])


def health(db: Session, user: User, srcs: list[dict], now: datetime | None = None) -> dict:
    """Context health from real state. Every statement is either a FACT (a count, a permission or a sync outcome) or
    the overall INFERENCE; the reasons are always returned so the UI can explain the state."""
    now = now or utcnow()
    connected = [s for s in srcs if s["state"] == "connected" and s["kind"] != "manual"]
    totals = _visible_counts(db, user)
    present = [t for t in CONTEXT_TYPES if totals.get(t, 0) > 0]
    missing = [t for t in CONTEXT_TYPES if t not in present]
    reasons: list[dict] = []

    if not connected:
        return {"state": "not_connected", "label": "Not connected", "claim_type": INFERENCE,
                "summary": "No organizational source is connected yet, so ROOK cannot build context.",
                "reasons": [{"text": "No source is connected.", "claim_type": FACT, "kind": "limitation"}],
                "coverage": {t: totals.get(t, 0) for t in CONTEXT_TYPES}, "synthetic": False}

    for t in present:
        reasons.append({"text": f"{CONTEXT_TYPES[t]}: {totals[t]} you can access.", "claim_type": FACT, "kind": "access"})
    for t in missing:
        reasons.append({"text": f"No {CONTEXT_TYPES[t].lower()} are available to ROOK yet.", "claim_type": FACT,
                        "kind": "limitation"})

    problems, limits = [], []
    for s in connected:
        c = s["connection"]
        if c["status"] in ("needs_reauth", "needs_configuration"):
            problems.append(f"{s['name']} needs attention ({c['status'].replace('_', ' ')}).")
        last_ok = _parse(c["last_successful_sync"])
        if last_ok is None:
            problems.append(f"{s['name']} has not completed a sync yet.")
        elif now - last_ok > STALE_AFTER:
            problems.append(f"{s['name']} was last synchronized more than 24 hours ago.")
        for a in c["access"]:
            if a["status"] not in ("available", "granted"):
                problems.append(f"{s['name']} · {a['label']}: {a['status_label'].lower()}.")
                limits.append(a["label"])
        for w in (c.get("last_sync") or {}).get("warnings", []):
            problems.append(f"{s['name']}: {w}")
    reasons += [{"text": p, "claim_type": FACT, "kind": "limitation"} for p in problems]

    core = {"meetings", "conversations"}
    if core <= set(present) and "transcripts" in present and ({"work_items", "documents"} & set(present)) and not problems:
        state, label = "strong", "Strong context"
        summary = "ROOK can access the meetings, conversations, transcripts and work items available to you, and every source is current."
    elif core <= set(present):
        state, label = "partial", "Partial context"
        gaps = limits + [CONTEXT_TYPES[t].lower() for t in missing if CONTEXT_TYPES[t].lower() not in {g.lower() for g in limits}]
        summary = ("ROOK can access your meetings and conversations"
                   + (f", but not {_join(gaps)}." if gaps else ", but a source needs attention or is out of date."))
    else:
        state, label = "limited", "Limited context"
        summary = "ROOK has a connection, but not enough usable data yet to build complete meeting context."
    synthetic = any(s["synthetic"] for s in connected)
    return {"state": state, "label": label, "claim_type": INFERENCE, "summary": summary, "reasons": reasons,
            "coverage": {t: totals.get(t, 0) for t in CONTEXT_TYPES}, "synthetic": synthetic}


def _join(items: list[str]) -> str:
    return items[0] if len(items) == 1 else f"{', '.join(items[:-1])} or {items[-1]}"


def context_overview(db: Session, user: User) -> dict:
    srcs = sources(db, user)
    return {"tagline": TAGLINE, "health": health(db, user, srcs), "sources": srcs,
            "available_later": available_later(srcs), "context_types": CONTEXT_TYPES}
